name: Deploy to Prod
on:
  push:
    tags:
      - v*

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tooling
        uses: ok-nick/setup-aftman@v0

      - run: rojo build -o game.rbxl
      - run: rbxcloud experience publish -f game.rbxl -p 11780824592 -u 4170318501 -t published -a ${{ secrets.API_KEY }}