name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tooling
        uses: ok-nick/setup-aftman@v0

      - run: rojo build -o game.rbxl
      - run: rbxcloud experience publish -f game.rbxl -p 11780832227 -u 4170320674 -t published -a ${{ secrets.API_KEY }}